version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chawrimart_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chawrimart_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: chawrimart_redis
    restart: always
    ports:
      - '6379:6379'

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chawrimart_backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_NAME: chawrimart_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 3000
      JWT_SECRET: supersecretkey
      JWT_EXPIRES_IN: 7d
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
